// Procedural polygon generation and the shared retro glow-stroke drawing style.

const TAU = Math.PI * 2

// Jittered polygon: 8-12 vertices at varied radii. `rand` is any ()=>0..1 fn.
export function makeAsteroidVerts(rand, radius) {
  const n = 8 + Math.floor(rand() * 5)
  const verts = []
  for (let i = 0; i < n; i++) {
    const ang = (i / n) * TAU + (rand() - 0.5) * (TAU / n) * 0.6
    const r = radius * (0.68 + rand() * 0.45)
    verts.push([Math.cos(ang) * r, Math.sin(ang) * r])
  }
  return verts
}

// Double-stroke "neon" effect: wide faint pass under a thin bright pass.
export function strokeGlowPoly(gfx, verts, color, { closed = true, alpha = 1 } = {}) {
  const pts = verts.map(([x, y]) => ({ x, y }))
  gfx.lineStyle(6, color, 0.18 * alpha)
  gfx.strokePoints(pts, closed, closed)
  gfx.lineStyle(1.5, color, 0.95 * alpha)
  gfx.strokePoints(pts, closed, closed)
}

export function strokeGlowLine(gfx, x1, y1, x2, y2, color, alpha = 1) {
  gfx.lineStyle(5, color, 0.16 * alpha)
  gfx.lineBetween(x1, y1, x2, y2)
  gfx.lineStyle(1.5, color, 0.9 * alpha)
  gfx.lineBetween(x1, y1, x2, y2)
}

export function randRange(rand, min, max) {
  return min + rand() * (max - min)
}

// A planet's outer capture boundary — its "atmosphere" edge. Objects inside
// get captured into orbit; outside it the planet exerts no pull at all.
// Scales with gravity (μ ∝ radius²): 85 → 280 px, 150 → 410 px.
export function planetCaptureRadius(radius) {
  return radius * 2 + 110
}

// A station's capture field is ARTIFICIAL — generated by its technology, not
// by mass — so every station projects the same fixed field regardless of size.
// μ and the orbit clamp are tuned so held orbits stay under the dock-speed
// gate (80): ~51 px/s at the field edge, ~64 at dock range.
export const STATION_CAPTURE_RADIUS = 190 // smallest planet ring is 280
export const STATION_FIELD_MU = 500_000
export const STATION_ORBIT_VMAX = 70 // clamp keeps inner orbits dockable
export const STATION_FIELD_INNER = 84 // rocks orbit clear of the ~70px structure

// A star's ring IS mass-based: the boundary where its pull fades below
// ~12 px/s². Derived from μ, not visual radius — red dwarf ≈ 428,
// main-sequence ≈ 532, blue giant ≈ 632, white dwarf ≈ 563, neutron ≈ 671:
// tiny heavy stars wear the biggest rings.
export function starCaptureRadius(strength) {
  return Math.sqrt(strength / 12)
}
